/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated session */
        get: operations["getAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current authenticated session */
        post: operations["logoutAuthSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh current authenticated session */
        post: operations["refreshAuthSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get login URL for auth flow */
        get: operations["getAuthLoginUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public health check endpoint */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /** Soft delete user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        KeycloakTokenClaims: {
            sub: string;
            /** Format: email */
            email: string;
            realm_access?: {
                roles?: string[];
            };
        };
        SessionUser: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            firstName?: string;
            lastName?: string;
        };
        AuthSession: {
            user: components["schemas"]["SessionUser"];
        };
        AuthRefreshResponse: components["schemas"]["AuthSession"];
        AuthLogoutResponse: {
            success: boolean;
            message?: string;
        };
        AuthLoginUrlResponse: {
            /** Format: uri */
            url: string;
        };
        /** @enum {string} */
        NotificationPriority: "low" | "normal" | "high" | "urgent";
        Notification: components["schemas"]["FullAuditFields"] & {
            title: string;
            body?: string;
            priority: components["schemas"]["NotificationPriority"];
            /** Format: date-time */
            readAt?: string | null;
        };
        SseNotificationNew: {
            /** @enum {string} */
            event: "notification.new";
            id: string;
            data: components["schemas"]["Notification"];
        };
        SseNotificationRead: {
            /** @enum {string} */
            event: "notification.read";
            id: string;
            data: {
                id: string;
                /** Format: date-time */
                readAt: string;
            };
        };
        SseNotificationArchived: {
            /** @enum {string} */
            event: "notification.archived";
            id: string;
            data: {
                id: string;
            };
        };
        SsePing: {
            /** @enum {string} */
            event: "ping";
            data: {
                /** Format: date-time */
                timestamp: string;
            };
        };
        SseNotificationEvent: components["schemas"]["SseNotificationNew"] | components["schemas"]["SseNotificationRead"] | components["schemas"]["SseNotificationArchived"] | components["schemas"]["SsePing"];
        User: components["schemas"]["FullAuditFields"] & {
            /** Format: email */
            email: string;
            displayName: string;
            firstName?: string;
            lastName?: string;
        };
        UserListItem: components["schemas"]["User"];
        UserListResponse: {
            data: components["schemas"]["UserListItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        UserProfile: {
            id: string;
            displayName: string;
        };
        ApiError: {
            statusCode: number;
            message: string;
            errorCode: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ValidationError: components["schemas"]["ApiError"];
        SuccessResponse: {
            success: boolean;
            message?: string;
        };
        /** @example {} */
        EmptyResponse: Record<string, never>;
        PaginationQuery: {
            /** @default 1 */
            page: number;
            /** @default 20 */
            limit: number;
            sort?: string;
            search?: string;
            /** @default false */
            withDeleted: boolean;
        };
        PaginationMeta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPrevPage: boolean;
        };
        AuditActor: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            firstName?: string;
            lastName?: string;
        };
        AuditFields: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            createdBy?: components["schemas"]["AuditActor"];
            updatedBy?: components["schemas"]["AuditActor"];
        };
        SoftDeleteFields: {
            /** Format: date-time */
            deletedAt?: string | null;
            deletedBy?: components["schemas"]["AuditActor"];
        };
        FullAuditFields: components["schemas"]["AuditFields"] & components["schemas"]["SoftDeleteFields"];
        /**
         * @description Aggregated status level for a service or the whole application.
         * @enum {string}
         */
        ServiceStatus: "ok" | "degraded" | "down";
        /** @description Runtime health information for a single named dependency or service. */
        ServiceHealth: {
            /** @description Current status of the service. */
            status: components["schemas"]["ServiceStatus"];
            /** @description Optional last observed response time in milliseconds. */
            responseTimeMs?: number;
            /** @description Optional human-readable diagnostic message. */
            message?: string;
        };
        /** @description Public health snapshot for the current application instance. */
        HealthResponse: {
            /** @description Aggregated application status derived from individual services. */
            status: components["schemas"]["ServiceStatus"];
            /** @description Current application version. */
            version: string;
            /**
             * Format: date-time
             * @description Timestamp when this health payload was created.
             */
            timestamp: string;
            /** @description Optional process uptime in whole seconds. */
            uptime?: number;
            /** @description Map of named services included in the health snapshot. */
            services: {
                [key: string]: components["schemas"]["ServiceHealth"];
            };
        };
    };
    responses: {
        /** @description Error response */
        DefaultApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    logoutAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLogoutResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    refreshAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed authenticated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRefreshResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    getAuthLoginUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login URL response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginUrlResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated users list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current local user projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User archived successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            default: components["responses"]["DefaultApiError"];
        };
    };
}
